blogs/urls.py
from django.urls import path

from blogs.views import BlogsListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    path('', BlogsListView.as_view(), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models


class AuthorModel(models.Model):
    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='blog-authors')
    about = models.TextField()
    position = models.CharField(max_length=128)
    profession = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'author'
        verbose_name_plural = 'authors'


class BlogCategoryModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class BlogTagModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class BlogModel(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='blog-images')
    content = models.TextField()
    short_info = models.TextField(null=True)
    category = models.ManyToManyField(BlogCategoryModel, related_name='blogs')
    tags = models.ManyToManyField(BlogTagModel, related_name='tags')
    authors = models.ForeignKey(AuthorModel, on_delete=models.CASCADE, related_name='blogs')

    test_editor = RichTextUploadingField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'

blogs/views.py
from django.views.generic import ListView, DetailView

from blogs.models import BlogModel, BlogCategoryModel, BlogTagModel


class BlogsListView(ListView):
    template_name = 'blogs/blog-list.html'
    context_object_name = 'blogs'
    paginate_by = 2

    def get_queryset(self):
        qs = BlogModel.objects.all().order_by('-pk')
        cat = self.request.GET.get('cat')
        tag = self.request.GET.get('tag')

        if cat:
            qs = qs.filter(category=cat)
        if tag:
            qs = qs.filter(tags=tag)

        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "category": BlogCategoryModel.objects.all(),
            "tags": BlogTagModel.objects.all(),
            "famous_blogs": BlogModel.objects.all().order_by('-created_at')[:2],
        })
        return context


class BlogDetailView(DetailView):
    template_name = 'blogs/blog-detail.html'
    context_object_name = 'blog'
    model = BlogModel

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {
            "category": BlogCategoryModel.objects.all(),
            "blog": BlogModel.objects.get(pk=self.kwargs['pk']),
            "tags": BlogTagModel.objects.all(),
            "famous_blogs": BlogModel.objects.all().order_by('created_at')[:2],
            "related_blogs": BlogModel.objects.filter(category__in=self.object.category.all())[:3]
        }
        return context

templates/blogs/blog-filter.html
{% load static %}
<div class="sidebar-3 sidebar-collection col-lg-3 col-md-3 col-sm-4">

                                        <!-- category -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Categories</div>
                                            <div class="block-content">
                                                {% for cat in category %}
                                                <div class="cateTitle hasSubCategory open level1">
                                                    <a {% if 'blogs/detail' in request.path %} href="{% url 'blogs:list' %}?cat={{ cat.pk }}" {% else %} style="cursor: pointer" class="cateItem" onclick="addUrlParameter('cat', '{{ cat.pk }}')"
                                                    {% endif %}
                                                    >{{ cat.name }}</a>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>

                                        <!-- recent posts -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Recent Posts</div>
                                            <div class="post-item-content">
                                                {% for blog in famous_blogs %}
                                                <div>
                                                    <div class="late-item first-child">
                                                        <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                            <p class="content-title">{{ blog.title}}</p>
                                                        </a>
                                                        <span>
                                                            <i class="zmdi zmdi-comments"></i>13 comment
                                                        </span>
                                                        <span>
                                                            <i class="zmdi zmdi-calendar-note"></i>{{ blog.created_at }}
                                                        </span>
                                                        <p class="description">{{ blog.short_info }}
                                                        </p>
                                                        <p class="remove">
                                                            <a href="{% url 'blogs:detail' pk=blog.id %}">READ MORE</a>
                                                        </p>
                                                    </div>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>

                                        <!-- product tag -->
                                        <div class="sidebar-block product-tags">
                                            <div class="title-block">
                                                Blog Tags
                                            </div>
                                            <div class="block-content">
                                                <ul class="listSidebarBlog list-unstyled">
                                                    {% for tag in tags %}
                                                    <li>
                                                        <a
                                                        {% if 'blogs/detail' in request.path %} href="{% url 'blogs:list' %}?tag={{ tag.id }}"
                                                        {% else %} style="cursor: pointer" onclick="addUrlParameter('tag', '{{ tag.pk }}')"
                                                        {% endif %}
                                                                 title="Show products matching tag Hot Trend">{{ tag.name }}</a>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>

                                        <!-- advertising -->
                                        <div class="sidebar-block group-image-special">
                                            <div class="effect">
                                                <a href="#">
                                                    <img class="img-fluid" src="{% static 'img/blog/advertising.jpg' %}" alt="banner-2" title="banner-2">
                                                </a>
                                            </div>
                                        </div>

                                    </div>

templates/blogs/blog-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">
                <div id="main">
                    <div class="page-home">

                        <!-- breadcrumb -->
                        <nav class="breadcrumb-bg">
                            <div class="container no-index">
                                <div class="breadcrumb">
                                    <ol>
                                        <li>
                                            <a href="#">
                                                <span>Home</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Living Room</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Sofa</span>
                                            </a>
                                        </li>
                                    </ol>
                                </div>
                            </div>
                        </nav>
                        <div class="container">
                            <div class="content">
                                <div class="row">
                                    {% include 'blogs/blog-filter.html' %}
                                    <div class="col-sm-8 col-lg-9 col-md-9 flex-xs-first main-blogs">
                                        <h2>Recent Posts</h2>
                                        {% for blog in blogs %}
                                        <div class="list-content row">
                                            <div class="hover-after col-md-5 col-xs-12">
                                                <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                    <img src="{{blog.image.url}}" alt="img">
                                                </a>
                                            </div>
                                            <div class="late-item col-md-7 col-xs-12">
                                                <p class="content-title">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}">{{ blog.title}}</a>
                                                </p>
                                                <p class="post-info">
                                                    <span>{{ blog.created_at }}</span>
                                                    <span>113 Comments</span>
                                                    <span>{{ blog.author.name }}</span>
                                                </p>
                                                <p class="description">{{ blog.short_info }}
                                                </p>
                                                <span class="view-more">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}">view more</a>
                                                </span>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        <div class="page-list col">
                                            <ul class="justify-content-center d-flex">
                                                <li>
                                                    <a rel="prev" href="{% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% else %}#{% endif %}" class="previous {% if not page_obj.has_previous %}disabled{% endif %} js-search-link">
                                                        Previous
                                                    </a>
                                                </li>
                                                {% for page in page_obj.paginator.page_range %}
                                                <li class="{% if page == page_obj.number %}current active{% endif %}">
                                                    <a rel="nofollow" href="?page={{ page }}" class="js-search-link">
                                                        {{ page }}
                                                    </a>
                                                </li>
                                                {% endfor %}
                                                <li>
                                                    <a rel="next" href="{% if page_obj.has_next %}{{ page_obj.next_page_number }}{% else %}#{% endif %}" class="next {% if not page_obj.has_next %}disabled{% endif %} js-search-link">
                                                        Next
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
        <script>
        function addUrlParameter(name, value) {
            let searchParams = new URLSearchParams(window.location.search)
            if (searchParams.has(name) && searchParams.get(name) === value) {
                searchParams.delete(name)
            } else {
                searchParams.set(name, value)
            }
            window.location.search = searchParams.toString()
        }
    </script>
{% endblock %}